### ISSUE TITLE
你好，10.15.4安装镜像+替换为这里的EFI，启动选择2安装后卡在logo（进度条50%多一点），请问哪里的问题

### ISSUE THREAD

**Issue by royatgh** [ififi2017/Hackintosh-NUC5i7RYH-EFI-10.15.2#2]
你好，10.15.4安装镜像+替换为这里的EFI，启动选择2安装后卡在logo（进度条50%多一点），请问哪里的问题？谢谢！
同款NUC5i7RYH。
bios已更新最新版本（2020 年 05 月 19 日 版本: 0385），bios关键设置如下，且已屏蔽wifi与蓝牙：
Boot->Boot Configuration, "Network Boot" 设置为 disabled

Power->Secondary Power Settings, "Wake on LAN from S4/S5", 设置为 "Stay Off"

Devices->USB, "xHCI Mode" 设置为 "Smart Auto"

Devices->Video, "IGD Minimum Memory" 设置为 64mb

Devices->Video, "IGD Aperture Size" 设置为 256mb

Boot->Secure Boot, "Secure Boot" 设置为 disabled

Security->Security Features, "Execute Disable Bit" 设置为 enabled

**Comment by ififi2017** [comment]
抱歉，我手上已经没有这个设备了，可以参考这个教程来配置OC。
https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/broadwell.html#starting-point
